version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
     - "3001:3001"
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
     - "3002:3002"
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
     - "3003:3003"
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
     - "3004:3004"
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  rabbitmq_network:
    driver: bridge
